/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fcmaes_core_Jni */

#ifndef _Included_fcmaes_core_Jni
#define _Included_fcmaes_core_Jni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeACMA
 * Signature: (Lutils/Fitness;[D[D[D[DIIDIIDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeACMA
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdouble, jint, jint, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeHawks
 * Signature: (Lutils/Fitness;[D[D[DIDIJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeHawks
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeDE
 * Signature: (Lutils/Fitness;[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeLDE
 * Signature: (Lutils/Fitness;[D[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeLDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeGCLDE
 * Signature: (Lutils/Fitness;[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeGCLDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeLCLDE
 * Signature: (Lutils/Fitness;[D[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeLCLDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeDA
 * Signature: (Lutils/Fitness;[D[D[DIIJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeDA
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integrateF8
 * Signature: ([DDDD)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integrateF8
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVthrust
 * Signature: ([DDDDDDD)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVthrust
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVgtocX
 * Signature: ([DDD)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVgtocX
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVCtoc11
 * Signature: ([DDDZ)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVCtoc11
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jboolean);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVCtoc11R
 * Signature: ([DDDZ)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVCtoc11R
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jboolean);


#ifdef __cplusplus
}
#endif
#endif
