/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fcmaes_examples_Jni */

#ifndef _Included_fcmaes_examples_Jni
#define _Included_fcmaes_examples_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fcmaes_examples_Jni
 * Method:    gtoc1_C
 * Signature: ([D[I[ID[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_gtoc1_1C
  (JNIEnv *, jclass, jdoubleArray, jintArray, jintArray, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    gtoc1part_C
 * Signature: ([D[I[ID[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_gtoc1part_1C
  (JNIEnv *, jclass, jdoubleArray, jintArray, jintArray, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    gtoc1back_C
 * Signature: ([D[I[ID[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_gtoc1back_1C
  (JNIEnv *, jclass, jdoubleArray, jintArray, jintArray, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    cassini1_C
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_cassini1_1C
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    sagas_C
 * Signature: ([DDD)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_sagas_1C
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    rosetta_C
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_rosetta_1C
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    cassini2_C
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_cassini2_1C
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    messenger_C
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_messenger_1C
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    messengerfull_C
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_messengerfull_1C
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    messengerpart_C
 * Signature: ([D[I[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_messengerpart_1C
  (JNIEnv *, jclass, jdoubleArray, jintArray, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    insertionDSM_C
 * Signature: ([D[IDD[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_insertionDSM_1C
  (JNIEnv *, jclass, jdoubleArray, jintArray, jdouble, jdouble, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    messengermga_C
 * Signature: ([D[I[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_messengermga_1C
  (JNIEnv *, jclass, jdoubleArray, jintArray, jdoubleArray);

/*
 * Class:     fcmaes_examples_Jni
 * Method:    tandem_C
 * Signature: ([D[I)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_examples_Jni_tandem_1C
  (JNIEnv *, jclass, jdoubleArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
