/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fcmaes_core_Jni */

#ifndef _Included_fcmaes_core_Jni
#define _Included_fcmaes_core_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeACMA
 * Signature: (Lfcmaes/core/Fitness;[D[D[D[DIIDIIDJIII)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeACMA
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdouble, jint, jint, jdouble, jlong, jint, jint, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    initCmaes
 * Signature: ([D[D[D[DIIDJIII)J
 */
JNIEXPORT jlong JNICALL Java_fcmaes_core_Jni_initCmaes
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdouble, jlong, jint, jint, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    destroyCmaes
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_destroyCmaes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fcmaes_core_Jni
 * Method:    askCmaes
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_fcmaes_core_Jni_askCmaes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fcmaes_core_Jni
 * Method:    tellCmaes
 * Signature: (J[DD)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_tellCmaes
  (JNIEnv *, jclass, jlong, jdoubleArray, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeDE
 * Signature: (Lfcmaes/core/Fitness;[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    initDE
 * Signature: ([D[D[DIDDDJI)J
 */
JNIEXPORT jlong JNICALL Java_fcmaes_core_Jni_initDE
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    destroyDE
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_destroyDE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fcmaes_core_Jni
 * Method:    askDE
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_fcmaes_core_Jni_askDE
  (JNIEnv *, jclass, jlong);

/*
 * Class:     fcmaes_core_Jni
 * Method:    tellDE
 * Signature: (J[DDI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_tellDE
  (JNIEnv *, jclass, jlong, jdoubleArray, jdouble, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integrateF8
 * Signature: ([DDDD)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integrateF8
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVthrust
 * Signature: ([DDDDDDD)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVthrust
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVgtocX
 * Signature: ([DDD)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVgtocX
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVCtoc11
 * Signature: ([DDDZ)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVCtoc11
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jboolean);

/*
 * Class:     fcmaes_core_Jni
 * Method:    integratePVCtoc11R
 * Signature: ([DDDZ)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_integratePVCtoc11R
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdouble, jboolean);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeHawks
 * Signature: (Lfcmaes/core/Fitness;[D[D[DIDIJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeHawks
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeLDE
 * Signature: (Lfcmaes/core/Fitness;[D[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeLDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeGCLDE
 * Signature: (Lfcmaes/core/Fitness;[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeGCLDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeLCLDE
 * Signature: (Lfcmaes/core/Fitness;[D[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeLCLDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeDA
 * Signature: (Lfcmaes/core/Fitness;[D[D[DIIJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeDA
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeCLDE
 * Signature: (Lfcmaes/core/Fitness;[D[D[DIDIDDDJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeCLDE
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jdouble, jdouble, jdouble, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeBite
 * Signature: (Lfcmaes/core/Fitness;[D[D[DIDIIJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeBite
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    optimizeCsma
 * Signature: (Lfcmaes/core/Fitness;[D[D[D[DIDIIJI)I
 */
JNIEXPORT jint JNICALL Java_fcmaes_core_Jni_optimizeCsma
  (JNIEnv *, jclass, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble, jint, jint, jlong, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    planetEplC
 * Signature: (ID[D[D)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_planetEplC
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_core_Jni
 * Method:    planetDataC
 * Signature: (ID[D)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_planetDataC
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray);

/*
 * Class:     fcmaes_core_Jni
 * Method:    iC2parC
 * Signature: ([D[DD[D)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_iC2parC
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     fcmaes_core_Jni
 * Method:    par2IC
 * Signature: ([DD[D[D)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_par2IC
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_core_Jni
 * Method:    fb_prop
 * Signature: ([D[DDDD[D)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_fb_1prop
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jdouble, jdouble, jdoubleArray);

/*
 * Class:     fcmaes_core_Jni
 * Method:    fb_vel
 * Signature: ([D[DI)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_core_Jni_fb_1vel
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     fcmaes_core_Jni
 * Method:    propagate_lagrangian
 * Signature: ([D[DDD)V
 */
JNIEXPORT void JNICALL Java_fcmaes_core_Jni_propagate_1lagrangian
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jdouble);

/*
 * Class:     fcmaes_core_Jni
 * Method:    propagateTAYC
 * Signature: ([D[DD[DDDDDD[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_core_Jni_propagateTAYC
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_core_Jni
 * Method:    propagateTAYJ2C
 * Signature: ([D[DD[DDDDDDD[D[D)D
 */
JNIEXPORT jdouble JNICALL Java_fcmaes_core_Jni_propagateTAYJ2C
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdouble, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray, jdoubleArray);

/*
 * Class:     fcmaes_core_Jni
 * Method:    lambertProblem
 * Signature: (DDDDDDDZID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_fcmaes_core_Jni_lambertProblem
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jboolean, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
